-- Create a view that maps lowercase columns to mixed case
CREATE VIEW "Courses" AS 
SELECT 
    id as "Id",
    title as "Title",
    description as "Description",
    short_description as "ShortDescription",
    instructor_id as "InstructorId",
    price as "Price",
    original_price as "OriginalPrice",
    discount as "Discount",
    duration as "Duration",
    level as "Level",
    category as "Category",
    thumbnail as "Thumbnail",
    thumbnail_url as "ThumbnailUrl",
    promo_video_url as "PromoVideoUrl",
    status as "Status",
    is_bestseller as "IsBestseller",
    features as "Features",
    preview_url as "PreviewUrl",
    enrollment_type as "EnrollmentType",
    is_published as "IsPublished",
    published_at as "PublishedAt",
    created_at as "CreatedAt",
    updated_at as "UpdatedAt",
    "CourseType",
    "PricingModel",
    "Currency",
    "SubscriptionPeriod",
    "PaymentPlanDetailsJson",
    "AccessType",
    "AccessDuration",
    "EnrollmentLimit",
    "Language",
    "HasCertificate",
    "HasCommunity",
    "HasLiveSessions",
    "HasDownloadableResources",
    "HasAssignments",
    "HasQuizzes",
    "DripContent",
    "DripScheduleJson",
    "AutomationWelcomeEmail",
    "AutomationCompletionCertificate",
    "AutomationProgressReminders",
    "AutomationAbandonmentSequence"
FROM courses;