-- Drop existing view if any
DROP VIEW IF EXISTS "Courses";

-- Create a view that properly maps all columns
CREATE VIEW "Courses" AS 
SELECT 
    id as "Id",
    title as "Title",
    description as "Description",
    "ShortDescription",
    instructor_id as "InstructorId",
    price as "Price",
    original_price as "OriginalPrice",
    NULL::integer as "Discount",
    duration as "Duration",
    level as "Level",
    category as "Category",
    thumbnail as "Thumbnail",
    NULL::text as "ThumbnailUrl",
    "PromoVideoUrl",
    status as "Status",
    is_bestseller as "IsBestseller",
    features as "Features",
    NULL::text as "PreviewUrl",
    'OneTime'::text as "EnrollmentType",
    "IsPublished",
    "PublishedAt",
    created_at as "CreatedAt",
    updated_at as "UpdatedAt",
    "CourseType",
    "PricingModel",
    "Currency",
    "SubscriptionPeriod",
    "PaymentPlanDetailsJson",
    "AccessType",
    "AccessDuration",
    "EnrollmentLimit",
    "Language",
    "HasCertificate",
    "HasCommunity",
    "HasLiveSessions",
    "HasDownloadableResources",
    "HasAssignments",
    "HasQuizzes",
    "DripContent",
    "DripScheduleJson",
    "AutomationWelcomeEmail",
    "AutomationCompletionCertificate",
    "AutomationProgressReminders",
    "AutomationAbandonmentSequence"
FROM courses;