CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);

START TRANSACTION;
CREATE TABLE "AspNetRoles" (
    "Id" text NOT NULL,
    "Name" character varying(256),
    "NormalizedName" character varying(256),
    "ConcurrencyStamp" text,
    CONSTRAINT "PK_AspNetRoles" PRIMARY KEY ("Id")
);

CREATE TABLE "AspNetUsers" (
    "Id" text NOT NULL,
    "FullName" text NOT NULL,
    "Avatar" text,
    "Role" text NOT NULL,
    "Status" text NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    "LastLoginAt" timestamp with time zone,
    "RefreshToken" text,
    "RefreshTokenExpiryTime" timestamp with time zone,
    "NotificationPreferences" text NOT NULL,
    "UserName" character varying(256),
    "NormalizedUserName" character varying(256),
    "Email" character varying(256),
    "NormalizedEmail" character varying(256),
    "EmailConfirmed" boolean NOT NULL,
    "PasswordHash" text,
    "SecurityStamp" text,
    "ConcurrencyStamp" text,
    "PhoneNumber" text,
    "PhoneNumberConfirmed" boolean NOT NULL,
    "TwoFactorEnabled" boolean NOT NULL,
    "LockoutEnd" timestamp with time zone,
    "LockoutEnabled" boolean NOT NULL,
    "AccessFailedCount" integer NOT NULL,
    CONSTRAINT "PK_AspNetUsers" PRIMARY KEY ("Id")
);

CREATE TABLE "AspNetRoleClaims" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "RoleId" text NOT NULL,
    "ClaimType" text,
    "ClaimValue" text,
    CONSTRAINT "PK_AspNetRoleClaims" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_AspNetRoleClaims_AspNetRoles_RoleId" FOREIGN KEY ("RoleId") REFERENCES "AspNetRoles" ("Id") ON DELETE CASCADE
);

CREATE TABLE "AspNetUserClaims" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "UserId" text NOT NULL,
    "ClaimType" text,
    "ClaimValue" text,
    CONSTRAINT "PK_AspNetUserClaims" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_AspNetUserClaims_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES "AspNetUsers" ("Id") ON DELETE CASCADE
);

CREATE TABLE "AspNetUserLogins" (
    "LoginProvider" text NOT NULL,
    "ProviderKey" text NOT NULL,
    "ProviderDisplayName" text,
    "UserId" text NOT NULL,
    CONSTRAINT "PK_AspNetUserLogins" PRIMARY KEY ("LoginProvider", "ProviderKey"),
    CONSTRAINT "FK_AspNetUserLogins_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES "AspNetUsers" ("Id") ON DELETE CASCADE
);

CREATE TABLE "AspNetUserRoles" (
    "UserId" text NOT NULL,
    "RoleId" text NOT NULL,
    CONSTRAINT "PK_AspNetUserRoles" PRIMARY KEY ("UserId", "RoleId"),
    CONSTRAINT "FK_AspNetUserRoles_AspNetRoles_RoleId" FOREIGN KEY ("RoleId") REFERENCES "AspNetRoles" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_AspNetUserRoles_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES "AspNetUsers" ("Id") ON DELETE CASCADE
);

CREATE TABLE "AspNetUserTokens" (
    "UserId" text NOT NULL,
    "LoginProvider" text NOT NULL,
    "Name" text NOT NULL,
    "Value" text,
    CONSTRAINT "PK_AspNetUserTokens" PRIMARY KEY ("UserId", "LoginProvider", "Name"),
    CONSTRAINT "FK_AspNetUserTokens_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES "AspNetUsers" ("Id") ON DELETE CASCADE
);

CREATE TABLE "Courses" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Title" text NOT NULL,
    "Description" text NOT NULL,
    "InstructorId" text NOT NULL,
    "Price" numeric NOT NULL,
    "OriginalPrice" numeric,
    "Discount" integer,
    "Duration" text NOT NULL,
    "Level" text NOT NULL,
    "Category" text NOT NULL,
    "Thumbnail" text,
    "Status" text NOT NULL,
    "IsBestseller" boolean NOT NULL,
    "Features" text NOT NULL,
    "PreviewUrl" text,
    "EnrollmentType" text NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    "UpdatedAt" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_Courses" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Courses_AspNetUsers_InstructorId" FOREIGN KEY ("InstructorId") REFERENCES "AspNetUsers" ("Id") ON DELETE RESTRICT
);

CREATE TABLE "InstructorApprovals" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "UserId" text NOT NULL,
    "Bio" text NOT NULL,
    "Qualifications" text NOT NULL,
    "TeachingExperience" text NOT NULL,
    "LinkedInProfile" text,
    "WebsiteUrl" text,
    "Status" text NOT NULL,
    "ReviewerNotes" text,
    "SubmittedAt" timestamp with time zone NOT NULL,
    "ReviewedAt" timestamp with time zone,
    "ReviewedBy" text,
    CONSTRAINT "PK_InstructorApprovals" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_InstructorApprovals_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES "AspNetUsers" ("Id") ON DELETE CASCADE
);

CREATE TABLE "Notifications" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "UserId" text NOT NULL,
    "Title" text NOT NULL,
    "Message" text NOT NULL,
    "Type" text NOT NULL,
    "IsRead" boolean NOT NULL,
    "ActionUrl" text,
    "CreatedAt" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_Notifications" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Notifications_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES "AspNetUsers" ("Id") ON DELETE CASCADE
);

CREATE TABLE "PasswordHistories" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "UserId" text NOT NULL,
    "PasswordHash" text NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_PasswordHistories" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_PasswordHistories_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES "AspNetUsers" ("Id") ON DELETE CASCADE
);

CREATE TABLE "RefreshTokens" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "UserId" text NOT NULL,
    "Token" text NOT NULL,
    "ExpiresAt" timestamp with time zone NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    "CreatedByIp" text,
    "RevokedAt" timestamp with time zone,
    "RevokedByIp" text,
    "ReplacedByToken" text,
    CONSTRAINT "PK_RefreshTokens" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_RefreshTokens_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES "AspNetUsers" ("Id") ON DELETE CASCADE
);

CREATE TABLE "Subscriptions" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "UserId" text NOT NULL,
    "PlanName" text NOT NULL,
    "Price" numeric NOT NULL,
    "BillingCycle" text NOT NULL,
    "Status" text NOT NULL,
    "StartDate" timestamp with time zone NOT NULL,
    "EndDate" timestamp with time zone,
    "NextBillingDate" timestamp with time zone,
    "StripeSubscriptionId" text,
    CONSTRAINT "PK_Subscriptions" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Subscriptions_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES "AspNetUsers" ("Id") ON DELETE CASCADE
);

CREATE TABLE "CourseModules" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "CourseId" integer NOT NULL,
    "Title" text NOT NULL,
    "Description" text,
    "Order" integer NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    "UpdatedAt" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_CourseModules" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_CourseModules_Courses_CourseId" FOREIGN KEY ("CourseId") REFERENCES "Courses" ("Id") ON DELETE CASCADE
);

CREATE TABLE "Enrollments" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "StudentId" text NOT NULL,
    "CourseId" integer NOT NULL,
    "EnrolledAt" timestamp with time zone NOT NULL,
    "CompletedAt" timestamp with time zone,
    "ProgressPercentage" double precision NOT NULL,
    "CertificateUrl" text,
    CONSTRAINT "PK_Enrollments" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Enrollments_AspNetUsers_StudentId" FOREIGN KEY ("StudentId") REFERENCES "AspNetUsers" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_Enrollments_Courses_CourseId" FOREIGN KEY ("CourseId") REFERENCES "Courses" ("Id") ON DELETE CASCADE
);

CREATE TABLE "Reviews" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "StudentId" text NOT NULL,
    "CourseId" integer NOT NULL,
    "Rating" integer NOT NULL,
    "Comment" text,
    "Status" text NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    "ApprovedAt" timestamp with time zone,
    "ApprovedBy" text,
    CONSTRAINT "PK_Reviews" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Reviews_AspNetUsers_StudentId" FOREIGN KEY ("StudentId") REFERENCES "AspNetUsers" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_Reviews_Courses_CourseId" FOREIGN KEY ("CourseId") REFERENCES "Courses" ("Id") ON DELETE CASCADE
);

CREATE TABLE "Payments" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "UserId" text NOT NULL,
    "CourseId" integer,
    "SubscriptionId" integer,
    "Amount" numeric NOT NULL,
    "Currency" text NOT NULL,
    "Status" text NOT NULL,
    "PaymentMethod" text NOT NULL,
    "TransactionId" text,
    "PaymentIntentId" text,
    "CreatedAt" timestamp with time zone NOT NULL,
    "ProcessedAt" timestamp with time zone,
    CONSTRAINT "PK_Payments" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Payments_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES "AspNetUsers" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_Payments_Courses_CourseId" FOREIGN KEY ("CourseId") REFERENCES "Courses" ("Id"),
    CONSTRAINT "FK_Payments_Subscriptions_SubscriptionId" FOREIGN KEY ("SubscriptionId") REFERENCES "Subscriptions" ("Id")
);

CREATE TABLE "Lessons" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "ModuleId" integer NOT NULL,
    "Title" text NOT NULL,
    "Duration" text NOT NULL,
    "Type" text NOT NULL,
    "Content" text,
    "VideoUrl" text,
    "Order" integer NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    "UpdatedAt" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_Lessons" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Lessons_CourseModules_ModuleId" FOREIGN KEY ("ModuleId") REFERENCES "CourseModules" ("Id") ON DELETE CASCADE
);

CREATE TABLE "LessonProgresses" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "StudentId" text NOT NULL,
    "LessonId" integer NOT NULL,
    "Status" text NOT NULL,
    "StartedAt" timestamp with time zone,
    "CompletedAt" timestamp with time zone,
    "QuizScore" integer,
    "AssignmentSubmissionUrl" text,
    CONSTRAINT "PK_LessonProgresses" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_LessonProgresses_AspNetUsers_StudentId" FOREIGN KEY ("StudentId") REFERENCES "AspNetUsers" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_LessonProgresses_Lessons_LessonId" FOREIGN KEY ("LessonId") REFERENCES "Lessons" ("Id") ON DELETE CASCADE
);

INSERT INTO "AspNetRoles" ("Id", "ConcurrencyStamp", "Name", "NormalizedName")
VALUES ('1', NULL, 'Admin', 'ADMIN');
INSERT INTO "AspNetRoles" ("Id", "ConcurrencyStamp", "Name", "NormalizedName")
VALUES ('2', NULL, 'Instructor', 'INSTRUCTOR');
INSERT INTO "AspNetRoles" ("Id", "ConcurrencyStamp", "Name", "NormalizedName")
VALUES ('3', NULL, 'Student', 'STUDENT');

CREATE INDEX "IX_AspNetRoleClaims_RoleId" ON "AspNetRoleClaims" ("RoleId");

CREATE UNIQUE INDEX "RoleNameIndex" ON "AspNetRoles" ("NormalizedName");

CREATE INDEX "IX_AspNetUserClaims_UserId" ON "AspNetUserClaims" ("UserId");

CREATE INDEX "IX_AspNetUserLogins_UserId" ON "AspNetUserLogins" ("UserId");

CREATE INDEX "IX_AspNetUserRoles_RoleId" ON "AspNetUserRoles" ("RoleId");

CREATE INDEX "EmailIndex" ON "AspNetUsers" ("NormalizedEmail");

CREATE UNIQUE INDEX "IX_AspNetUsers_Email" ON "AspNetUsers" ("Email");

CREATE UNIQUE INDEX "UserNameIndex" ON "AspNetUsers" ("NormalizedUserName");

CREATE INDEX "IX_CourseModules_CourseId" ON "CourseModules" ("CourseId");

CREATE INDEX "IX_Courses_Category" ON "Courses" ("Category");

CREATE INDEX "IX_Courses_InstructorId" ON "Courses" ("InstructorId");

CREATE INDEX "IX_Courses_Status" ON "Courses" ("Status");

CREATE INDEX "IX_Enrollments_CourseId" ON "Enrollments" ("CourseId");

CREATE UNIQUE INDEX "IX_Enrollments_StudentId_CourseId" ON "Enrollments" ("StudentId", "CourseId");

CREATE UNIQUE INDEX "IX_InstructorApprovals_UserId" ON "InstructorApprovals" ("UserId");

CREATE INDEX "IX_LessonProgresses_LessonId" ON "LessonProgresses" ("LessonId");

CREATE UNIQUE INDEX "IX_LessonProgresses_StudentId_LessonId" ON "LessonProgresses" ("StudentId", "LessonId");

CREATE INDEX "IX_Lessons_ModuleId" ON "Lessons" ("ModuleId");

CREATE INDEX "IX_Notifications_UserId" ON "Notifications" ("UserId");

CREATE INDEX "IX_PasswordHistories_UserId" ON "PasswordHistories" ("UserId");

CREATE INDEX "IX_Payments_CourseId" ON "Payments" ("CourseId");

CREATE INDEX "IX_Payments_SubscriptionId" ON "Payments" ("SubscriptionId");

CREATE INDEX "IX_Payments_UserId" ON "Payments" ("UserId");

CREATE INDEX "IX_RefreshTokens_ExpiresAt" ON "RefreshTokens" ("ExpiresAt");

CREATE UNIQUE INDEX "IX_RefreshTokens_Token" ON "RefreshTokens" ("Token");

CREATE INDEX "IX_RefreshTokens_UserId" ON "RefreshTokens" ("UserId");

CREATE INDEX "IX_Reviews_CourseId" ON "Reviews" ("CourseId");

CREATE INDEX "IX_Reviews_StudentId" ON "Reviews" ("StudentId");

CREATE INDEX "IX_Subscriptions_UserId" ON "Subscriptions" ("UserId");

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20250725044538_InitialCreate', '9.0.7');

ALTER TABLE "Subscriptions" ADD "CreatedAt" timestamp with time zone NOT NULL DEFAULT TIMESTAMPTZ '-infinity';

ALTER TABLE "Subscriptions" ADD "SubscriptionPlanId" integer NOT NULL DEFAULT 0;

ALTER TABLE "Subscriptions" ADD "UpdatedAt" timestamp with time zone NOT NULL DEFAULT TIMESTAMPTZ '-infinity';

CREATE TABLE "SubscriptionPlans" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Name" text NOT NULL,
    "Description" text NOT NULL,
    "MonthlyPrice" numeric NOT NULL,
    "YearlyPrice" numeric NOT NULL,
    "MaxCourseAccess" integer NOT NULL,
    "HasUnlimitedAccess" boolean NOT NULL,
    "Features" text NOT NULL,
    "IsActive" boolean NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    "UpdatedAt" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_SubscriptionPlans" PRIMARY KEY ("Id")
);

CREATE INDEX "IX_Subscriptions_SubscriptionPlanId" ON "Subscriptions" ("SubscriptionPlanId");

ALTER TABLE "Subscriptions" ADD CONSTRAINT "FK_Subscriptions_SubscriptionPlans_SubscriptionPlanId" FOREIGN KEY ("SubscriptionPlanId") REFERENCES "SubscriptionPlans" ("Id") ON DELETE RESTRICT;

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20250725153609_AddSubscriptionPlans', '9.0.7');

ALTER TABLE "Enrollments" ADD "AverageQuizScore" double precision;

ALTER TABLE "Enrollments" ADD "CertificateIssued" boolean NOT NULL DEFAULT FALSE;

ALTER TABLE "Enrollments" ADD "CompletedLessons" integer NOT NULL DEFAULT 0;

ALTER TABLE "Enrollments" ADD "LastAccessedDate" timestamp with time zone;

ALTER TABLE "Enrollments" ADD "QuizCount" integer;

ALTER TABLE "Enrollments" ADD "TotalTimeSpent" integer NOT NULL DEFAULT 0;

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20250728085358_FixModelChanges', '9.0.7');

ALTER TABLE "SubscriptionPlans" ADD "DisplayOrder" integer NOT NULL DEFAULT 0;

ALTER TABLE "SubscriptionPlans" ADD "HasAnalytics" boolean NOT NULL DEFAULT FALSE;

ALTER TABLE "SubscriptionPlans" ADD "HasPrioritySupport" boolean NOT NULL DEFAULT FALSE;

ALTER TABLE "SubscriptionPlans" ADD "IsRecommended" boolean NOT NULL DEFAULT FALSE;

ALTER TABLE "SubscriptionPlans" ADD "MaxCoursesCanCreate" integer;

ALTER TABLE "SubscriptionPlans" ADD "MaxStudentsPerCourse" integer;

ALTER TABLE "SubscriptionPlans" ADD "PlanType" integer NOT NULL DEFAULT 0;

ALTER TABLE "SubscriptionPlans" ADD "TransactionFeePercentage" numeric;

ALTER TABLE "Reviews" ADD "IsFlagged" boolean NOT NULL DEFAULT FALSE;

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20250728152206_AddSubscriptionAndReviewFields', '9.0.7');

ALTER TABLE "Courses" ALTER COLUMN "Duration" DROP NOT NULL;

ALTER TABLE "Courses" ADD "AccessDuration" integer;

ALTER TABLE "Courses" ADD "AccessType" integer NOT NULL DEFAULT 0;

ALTER TABLE "Courses" ADD "AutomationAbandonmentSequence" boolean NOT NULL DEFAULT FALSE;

ALTER TABLE "Courses" ADD "AutomationCompletionCertificate" boolean NOT NULL DEFAULT FALSE;

ALTER TABLE "Courses" ADD "AutomationProgressReminders" boolean NOT NULL DEFAULT FALSE;

ALTER TABLE "Courses" ADD "AutomationWelcomeEmail" boolean NOT NULL DEFAULT FALSE;

ALTER TABLE "Courses" ADD "CourseType" integer NOT NULL DEFAULT 0;

ALTER TABLE "Courses" ADD "Currency" text NOT NULL DEFAULT '';

ALTER TABLE "Courses" ADD "DripContent" boolean NOT NULL DEFAULT FALSE;

ALTER TABLE "Courses" ADD "DripScheduleJson" text;

ALTER TABLE "Courses" ADD "EnrollmentLimit" integer;

ALTER TABLE "Courses" ADD "HasAssignments" boolean NOT NULL DEFAULT FALSE;

ALTER TABLE "Courses" ADD "HasCertificate" boolean NOT NULL DEFAULT FALSE;

ALTER TABLE "Courses" ADD "HasCommunity" boolean NOT NULL DEFAULT FALSE;

ALTER TABLE "Courses" ADD "HasDownloadableResources" boolean NOT NULL DEFAULT FALSE;

ALTER TABLE "Courses" ADD "HasLiveSessions" boolean NOT NULL DEFAULT FALSE;

ALTER TABLE "Courses" ADD "HasQuizzes" boolean NOT NULL DEFAULT FALSE;

ALTER TABLE "Courses" ADD "IsPublished" boolean NOT NULL DEFAULT FALSE;

ALTER TABLE "Courses" ADD "Language" text NOT NULL DEFAULT '';

ALTER TABLE "Courses" ADD "PaymentPlanDetailsJson" text;

ALTER TABLE "Courses" ADD "PricingModel" integer NOT NULL DEFAULT 0;

ALTER TABLE "Courses" ADD "PromoVideoUrl" text;

ALTER TABLE "Courses" ADD "PublishedAt" timestamp with time zone;

ALTER TABLE "Courses" ADD "ShortDescription" text;

ALTER TABLE "Courses" ADD "SubscriptionPeriod" integer;

ALTER TABLE "Courses" ADD "ThumbnailUrl" text;

CREATE TABLE "CourseApprovals" (
    "Id" uuid NOT NULL,
    "CourseId" integer NOT NULL,
    "SubmittedById" text NOT NULL,
    "ReviewedById" text,
    "Status" text NOT NULL,
    "Feedback" text,
    "SubmittedAt" timestamp with time zone NOT NULL,
    "ReviewedAt" timestamp with time zone,
    "CreatedAt" timestamp with time zone NOT NULL,
    "UpdatedAt" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_CourseApprovals" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_CourseApprovals_AspNetUsers_ReviewedById" FOREIGN KEY ("ReviewedById") REFERENCES "AspNetUsers" ("Id") ON DELETE RESTRICT,
    CONSTRAINT "FK_CourseApprovals_AspNetUsers_SubmittedById" FOREIGN KEY ("SubmittedById") REFERENCES "AspNetUsers" ("Id") ON DELETE RESTRICT,
    CONSTRAINT "FK_CourseApprovals_Courses_CourseId" FOREIGN KEY ("CourseId") REFERENCES "Courses" ("Id") ON DELETE CASCADE
);

CREATE INDEX "IX_CourseApprovals_CourseId" ON "CourseApprovals" ("CourseId");

CREATE INDEX "IX_CourseApprovals_ReviewedById" ON "CourseApprovals" ("ReviewedById");

CREATE INDEX "IX_CourseApprovals_SubmittedById" ON "CourseApprovals" ("SubmittedById");

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20250730093650_AddGoHighLevelCourseFields', '9.0.7');

COMMIT;

