-- Add Go High Level specific columns to courses table (lowercase)
ALTER TABLE courses ADD COLUMN IF NOT EXISTS "CourseType" integer NOT NULL DEFAULT 3;
ALTER TABLE courses ADD COLUMN IF NOT EXISTS "PricingModel" integer NOT NULL DEFAULT 1;
ALTER TABLE courses ADD COLUMN IF NOT EXISTS "Currency" text NOT NULL DEFAULT 'PHP';
ALTER TABLE courses ADD COLUMN IF NOT EXISTS "SubscriptionPeriod" integer;
ALTER TABLE courses ADD COLUMN IF NOT EXISTS "PaymentPlanDetailsJson" text;
ALTER TABLE courses ADD COLUMN IF NOT EXISTS "AccessType" integer NOT NULL DEFAULT 0;
ALTER TABLE courses ADD COLUMN IF NOT EXISTS "AccessDuration" integer;
ALTER TABLE courses ADD COLUMN IF NOT EXISTS "EnrollmentLimit" integer;
ALTER TABLE courses ADD COLUMN IF NOT EXISTS "Language" text NOT NULL DEFAULT 'en';
ALTER TABLE courses ADD COLUMN IF NOT EXISTS "HasCertificate" boolean NOT NULL DEFAULT false;
ALTER TABLE courses ADD COLUMN IF NOT EXISTS "HasCommunity" boolean NOT NULL DEFAULT false;
ALTER TABLE courses ADD COLUMN IF NOT EXISTS "HasLiveSessions" boolean NOT NULL DEFAULT false;
ALTER TABLE courses ADD COLUMN IF NOT EXISTS "HasDownloadableResources" boolean NOT NULL DEFAULT false;
ALTER TABLE courses ADD COLUMN IF NOT EXISTS "HasAssignments" boolean NOT NULL DEFAULT false;
ALTER TABLE courses ADD COLUMN IF NOT EXISTS "HasQuizzes" boolean NOT NULL DEFAULT false;
ALTER TABLE courses ADD COLUMN IF NOT EXISTS "DripContent" boolean NOT NULL DEFAULT false;
ALTER TABLE courses ADD COLUMN IF NOT EXISTS "DripScheduleJson" text;
ALTER TABLE courses ADD COLUMN IF NOT EXISTS "AutomationWelcomeEmail" boolean NOT NULL DEFAULT true;
ALTER TABLE courses ADD COLUMN IF NOT EXISTS "AutomationCompletionCertificate" boolean NOT NULL DEFAULT true;
ALTER TABLE courses ADD COLUMN IF NOT EXISTS "AutomationProgressReminders" boolean NOT NULL DEFAULT true;
ALTER TABLE courses ADD COLUMN IF NOT EXISTS "AutomationAbandonmentSequence" boolean NOT NULL DEFAULT false;
ALTER TABLE courses ADD COLUMN IF NOT EXISTS "IsPublished" boolean NOT NULL DEFAULT false;
ALTER TABLE courses ADD COLUMN IF NOT EXISTS "PublishedAt" timestamp with time zone;
ALTER TABLE courses ADD COLUMN IF NOT EXISTS "ShortDescription" text;
ALTER TABLE courses ADD COLUMN IF NOT EXISTS "PromoVideoUrl" text;